#!/usr/bin/env bash
set -Eeuo pipefail

# The Generation-20 runtime installation, proven in a fixture.
#
# UNPRIVILEGED AND ISOLATED. Every path the installer touches is rebound under
# --fixture. No production runtime object is read for state and none is written;
# no sudo, no helper, no Podman, no container, no invocation, and no
# administrative record.
#
# WHAT GENERATION 20 IS
# =====================
# FIVE objects, in ONE coherence group (P), one of them a CREATE:
#
#   backing_store.py   REPLACE, published FIRST -- adds target_fingerprint
#   admin.py           REPLACE                  -- adds the closed-set verb
#   abandonment.py     REPLACE                  -- reports the root it held
#   provenance.py      CREATE                   -- the correction operation
#   cli.py             REPLACE, published LAST  -- explicit --store-root, and
#                                                  the new operator surface
#
# WHAT THIS SUITE IS FOR, BEYOND "THE INSTALLER WORKS"
# ====================================================
#   * THE ORDER IS THE SAFETY PROPERTY, AND IT IS AN IMPORT-GRAPH ONE. Four of
#     the five sit on one chain, and `cli.py` imports `abandonment` and
#     `provenance` at MODULE level -- so a wrong order is an ImportError on
#     every command, including `recover`. Each intermediate is not argued about:
#     `tools.capability.cli` is imported against it.
#   * NO INTERMEDIATE MAY EXPOSE THE NEW VERB. The operator surface publishes
#     last, so there is no window in which a correction can be recorded through
#     an implicitly resolved root.
#   * THE BREAKING CHANGE IS DELIBERATE AND IS ASSERTED. After installation,
#     `abandon` without --store-root is a usage error rather than a mutation of
#     production. That is the defect this generation exists to remove.
#
# THE FIXTURE IS THE INSTALLED GENERATION-19 SURFACE. Unlike earlier generation
# suites, no reconstruction from git history is needed: Generation 19 is what is
# installed, it was independently verified at G11-BC-X, and the fixture is a
# copy of it. The evidence files the installer requires of its predecessor are
# generated by hashing that copy, which is what the real ones record.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
INSTALLER="${ROOT}/provisioning/execution/install-generation-20.sh"
CEREMONY="${ROOT}/provisioning/execution/gen20-operator-ceremony.txt"

# HOST-ONLY: the fixture IS the installed runtime, so there is nothing to build
# on a machine without one.
# shellcheck source=tests/lib/host-only.sh disable=SC1091
. "${SCRIPT_DIR}/lib/host-only.sh"
# shellcheck source=tests/lib/succession.sh disable=SC1091
. "${SCRIPT_DIR}/lib/succession.sh"
host_only_requires /usr/lib/kyri/python          # prod-path-reference

INSTALLED=/usr/lib/kyri/python                   # prod-path-reference

GEN20_COMMIT="$(sed -n 's/^COMMIT="\([0-9a-f]\{40\}\)"$/\1/p' "${INSTALLER}")"
GEN19_COMMIT="$(sed -n 's/^GEN19_COMMIT="\([0-9a-f]\{40\}\)"$/\1/p' "${INSTALLER}")"
[[ -n "${GEN20_COMMIT}" && -n "${GEN19_COMMIT}" ]] \
  || { printf 'cannot read the source authorities from the installer\n' >&2; exit 1; }

# The declared rows, read rather than restated, so the suite cannot disagree
# with the thing it tests.
matrix_rows() { sed -n '/^MATRIX=(/,/^)$/p' "${INSTALLER}" | grep '^"'; }
row_for()   { matrix_rows | grep -F "\"$1|" | head -1; }
# The row is stored quoted, so the last field carries a trailing quote. Strip
# both ends rather than only comparing fields that happen not to be last.
row_field() { local v; v="$(printf '%s' "$1" | cut -d'|' -f"$2")"; v="${v#\"}"; printf '%s' "${v%\"}"; }
base_of() { row_field "$(row_for "$1")" 5; }
want_of() { row_field "$(row_for "$1")" 6; }
op_of()   { row_field "$(row_for "$1")" 4; }

GEN20_SOURCES=(
"tools/capability/execution/backing_store.py"
"tools/capability/execution/admin.py"
"tools/capability/execution/abandonment.py"
"tools/capability/execution/provenance.py"
"tools/capability/cli.py"
)
for _src in "${GEN20_SOURCES[@]}"; do
  [[ -n "$(row_for "${_src}")" ]] \
    || { printf 'cannot read the declared Generation-20 row for %s\n' "${_src}" >&2; exit 1; }
done

FAILURES=0
pass() { printf 'PASS: %s\n' "$1"; }
fail() { printf 'FAIL: %s\n' "$1" >&2; FAILURES=$((FAILURES + 1)); }

WORK="$(mktemp -d)"
trap 'chmod -R u+w "${WORK}" 2>/dev/null || true; rm -rf "${WORK}"' EXIT

INSTALLED_BEFORE="$(find "${INSTALLED}" -type f -name '*.py' -print0 | sort -z \
                    | xargs -0 sha256sum | sha256sum | cut -d' ' -f1)"

digest_at() {
  local path="$1/usr/lib/kyri/python/$2"
  [[ -f "${path}" ]] || { printf 'ABSENT'; return 0; }
  sha256sum "${path}" | cut -d' ' -f1
}
library_count() { find "$1/usr/lib/kyri/python" -type f -name '*.py' | wc -l; }
manifest() {
  { find "$1" -printf '%P %m %s\n' | sort
    find "$1" -type f -print0 | sort -z | xargs -0 -r sha256sum | sed "s|${1}||"; } \
  | sha256sum | cut -d' ' -f1
}

declared_helper_paths() {
  PYTHONDONTWRITEBYTECODE=1 python3 - <<'HELPERPY'
import importlib.util, sys
spec = importlib.util.spec_from_file_location(
    "installed_helpers",
    "/usr/lib/kyri/python/tools/capability/execution/helpers.py")  # prod-path-reference
mod = importlib.util.module_from_spec(spec)
sys.modules["installed_helpers"] = mod
spec.loader.exec_module(mod)
for helper in mod.REQUIRED_HELPERS:
    print(helper.path)
HELPERPY
}

build_fixture() {
  local root="$1"
  [[ -e "${root}" ]] && { chmod -R u+w "${root}"; rm -rf "${root}"; }
  local lib="${root}/usr/lib/kyri/python"
  mkdir -p "${lib}" "${root}/usr/libexec" "${root}/root" "${root}/etc/sudoers.d"
  mkdir -p "${root}/etc/kyri"                                       # prod-path-reference
  mkdir -p "${root}/var/lib/kyri/implementation-authority"          # prod-path-reference
  mkdir -p "${root}/var/lib/kyri/implementation-authority-control"  # prod-path-reference

  # The Generation-19 surface, RECONSTRUCTED.
  #
  # This suite copied the installed library and called it Generation 19, which
  # was true for exactly as long as Generation 20 was unpublished. The operator
  # installed it on 2026-09-21 and the copy became a Generation-20 tree
  # claiming to be its own predecessor -- the same defect eight earlier
  # generation suites carried, corrected at G11-BC-Y. So the PATH SET comes
  # from the live library and the BYTES of everything this generation moves are
  # rewound to the reviewed Generation-19 commit.
  local object
  while IFS= read -r object; do
    install -D -m 0444 "${INSTALLED}/${object}" "${lib}/${object}"
  done < <( cd "${INSTALLED}" && find . -type f -name '*.py' ! -path '*__pycache__*' \
              -printf '%P\n' | sort )
  succession_rewind "${lib}" "${ROOT}" "${GEN19_COMMIT}" "${INSTALLER}" \
    || { printf 'FIXTURE: the Generation-19 reconstruction failed\n' >&2; return 1; }

  # The predecessor evidence, which records exactly that surface.
  local evidence="${root}/root/kyri-gen19-library-digests.txt"
  : > "${evidence}"
  while IFS= read -r object; do
    printf '%s  /usr/lib/kyri/python/%s\n' \
      "$(sha256sum "${lib}/${object}" | cut -d' ' -f1)" "${object}" >> "${evidence}"
  done < <( cd "${lib}" && find . -type f -name '*.py' -printf '%P\n' | sort )

  local helper
  while IFS= read -r helper; do
    [[ "${helper}" == /usr/libexec/* ]] || continue
    install -D -m 0555 "${helper}" "${root}${helper}"   # prod-path-reference
  done < <(declared_helper_paths)

  : > "${root}/root/kyri-gen19-helper-digests.txt"
  local entrypoint
  for entrypoint in /usr/libexec/kyri-exec-*; do        # prod-path-reference
    [[ -f "${entrypoint}" ]] || continue
    printf '%s  %s\n' "$(sha256sum "${entrypoint}" | cut -d' ' -f1)" "${entrypoint}" \
      >> "${root}/root/kyri-gen19-helper-digests.txt"
  done

  printf 'Cmnd_Alias KYRI_EXEC_LAUNCH = sha256:%s \\\n    /usr/libexec/kyri-exec-transition ^CINV-[0-9]{6}$\ncschott ALL=(root) NOPASSWD: KYRI_EXEC_LAUNCH\n' \
    "$(sha256sum /usr/libexec/kyri-exec-transition | cut -d' ' -f1)" \
    > "${root}/etc/sudoers.d/kyri-exec-launch"
  printf 'Cmnd_Alias KYRI_EXEC_RECONCILE = sha256:%s \\\n    /usr/libexec/kyri-exec-reconcile ^CINV-[0-9]{6}$\ncschott ALL=(root) NOPASSWD: KYRI_EXEC_RECONCILE\n' \
    "$(sha256sum /usr/libexec/kyri-exec-reconcile | cut -d' ' -f1)" \
    > "${root}/etc/sudoers.d/kyri-exec-reconcile"
  chmod 0440 "${root}/etc/sudoers.d/kyri-exec-launch" "${root}/etc/sudoers.d/kyri-exec-reconcile"

  printf '{"coordinator_account":"cschott","coordinator_uid":1000,"schema_version":1}\n' \
    > "${root}/etc/kyri/coordinator-identity.json"  # prod-path-reference
  printf '{"execution_account":"kyri-capability","execution_gid":987,"execution_uid":999,"schema_version":1}\n' \
    > "${root}/etc/kyri/execution-identity.json"    # prod-path-reference
}

run_installer() {
  local root="$1" mode="$2"
  shift 2
  ( cd "${ROOT}" && env "$@" PYTHONDONTWRITEBYTECODE=1 \
      bash "${INSTALLER}" "${mode}" --fixture "${root}" ) \
    > "${WORK}/last-run.log" 2>&1
}

# ===========================================================================
# 1. The declaration
# ===========================================================================

printf -- '--- the declaration ---\n'

# NOT EXECUTABLE is the property; the exact mode is not. Git records only the
# executable bit, so a fresh clone under a different umask carries 664 and an
# assertion on 644 fails there while proving nothing about the thing that
# matters -- the provisioning suite refuses an executable under this directory.
if [[ ! -x "${INSTALLER}" ]]; then
  pass "the installer is not executable: it is run by an operator through bash, deliberately"
else
  fail "the installer is executable (mode $(stat -c '%a' "${INSTALLER}"))"
fi

if [[ "$(matrix_rows | wc -l)" == "5" ]]; then
  pass "the matrix declares exactly five objects"
else
  fail "the matrix declares $(matrix_rows | wc -l) objects"
fi

order="$(sed -n '/^PUBLICATION_ORDER=(/,/^)$/p' "${INSTALLER}" | sed -n 's/^"\(.*\)"$/\1/p')"
expected_order="$(printf '%s\n' "${GEN20_SOURCES[@]}")"
if [[ "${order}" == "${expected_order}" ]]; then
  pass "the declared publication order is backing_store, admin, abandonment, provenance, cli"
else
  fail "the declared order is: ${order}"
fi

if [[ "$(matrix_rows | head -1)" == *"backing_store.py"* ]]; then
  pass "backing_store.py is row one: the name everything else imports"
else
  fail "row one is not backing_store.py"
fi
if [[ "$(matrix_rows | tail -1)" == *"cli.py"* ]]; then
  pass "cli.py is the last row: no intermediate exposes the new verb"
else
  fail "the last row is not cli.py"
fi

if [[ "$(op_of tools/capability/execution/provenance.py)" == "CREATE" ]] \
   && [[ "$(base_of tools/capability/execution/provenance.py)" == "ABSENT" ]]; then
  pass "provenance.py is the one CREATE, declared ABSENT at Generation 19"
else
  fail "provenance.py is not declared as a CREATE from ABSENT"
fi

for source in "${GEN20_SOURCES[@]}"; do
  [[ "$(row_field "$(row_for "${source}")" 7)" == "P" ]] \
    || fail "${source} is not in coherence group P"
done
pass "every row is in coherence group P"

# The declared baselines are what the reviewed Generation-19 commit carries.
# NOT what is installed: the host is at Generation 20 now, and asking the host
# what its own predecessor was is the question that goes stale.
drift=0
for source in "${GEN20_SOURCES[@]}"; do
  declared="$(base_of "${source}")"
  # Asked, not inferred: a CREATE row's path is simply not in that commit, and
  # under pipefail a `git show` of it would take the suite down rather than
  # report.
  if git -C "${ROOT}" cat-file -e "${GEN19_COMMIT}:${source}" 2>/dev/null; then
    actual="$(git -C "${ROOT}" show "${GEN19_COMMIT}:${source}" | sha256sum | cut -d' ' -f1)"
  else
    actual="ABSENT"
  fi
  [[ "${declared}" == "${actual}" ]] \
    || { fail "${source}: declared baseline ${declared}, reviewed Generation 19 ${actual}"; drift=1; }
done
(( drift == 0 )) && pass "every declared baseline matches the reviewed Generation-19 commit ${GEN19_COMMIT:0:7}"

# And the targets are what IS installed, because the operator installed them.
drift=0
for source in "${GEN20_SOURCES[@]}"; do
  declared="$(want_of "${source}")"
  actual="$(sha256sum "${INSTALLED}/${source}" 2>/dev/null | cut -d' ' -f1)"
  [[ "${declared}" == "${actual}" ]] \
    || { fail "${source}: declared target ${declared}, installed ${actual:-absent}"; drift=1; }
done
(( drift == 0 )) && pass "every declared target matches what the operator installed"

drift=0
for source in "${GEN20_SOURCES[@]}"; do
  declared="$(want_of "${source}")"
  actual="$(git -C "${ROOT}" show "${GEN20_COMMIT}:${source}" | sha256sum | cut -d' ' -f1)"
  [[ "${declared}" == "${actual}" ]] || { fail "${source}: declared target ${declared}, reviewed ${actual}"; drift=1; }
done
(( drift == 0 )) && pass "every declared target matches the reviewed bytes at ${GEN20_COMMIT:0:7}"

# ===========================================================================
# 2. Source verification
# ===========================================================================

printf -- '\n--- source verification ---\n'

# --verify-source reads REVIEWED BYTES, so it refuses a dirty working tree by
# design. That is the ceremony's property, not a problem to work around: when
# the tree is dirty the checks below cannot be run at all, and saying so is
# honest where claiming a pass would not be.
SOURCE_VERIFIED=1
if [[ -n "$(git -C "${ROOT}" status --porcelain)" ]]; then
  SOURCE_VERIFIED=0
  printf 'NOTE: the working tree is dirty, so --verify-source cannot run.\n'
  printf '      It reads reviewed bytes only. Commit, then re-run this suite.\n'
elif ( cd "${ROOT}" && bash "${INSTALLER}" --verify-source ) > "${WORK}/source.log" 2>&1; then
  pass "--verify-source accepts the reviewed bytes"
else
  SOURCE_VERIFIED=0
  fail "--verify-source refused: $(tail -3 "${WORK}/source.log" | tr '\n' ' ')"
fi
for property in \
  "fingerprints the descriptor itself" \
  "adds CORRECT_PROVENANCE to the closed set with no destruction authority" \
  "takes the CINV lock only, writes no transition, and corrects no lifecycle claim" \
  "digests its subject, opens nothing for writing" \
  "requires an explicit target for both administrative mutators" \
  "fingerprint the root they hold" \
  "no target-state flag" \
  "ADR-0015 intact"
do
  if (( SOURCE_VERIFIED == 0 )); then
    continue
  fi
  if grep -qF "${property}" "${WORK}/source.log"; then
    pass "proved from the reviewed bytes: ${property}"
  else
    fail "--verify-source did not prove: ${property}"
  fi
done

# ===========================================================================
# 3. The transaction
# ===========================================================================

printf -- '\n--- the transaction ---\n'

root="${WORK}/fixture"
build_fixture "${root}"
before_manifest="$(manifest "${root}")"
before_count="$(library_count "${root}")"

# The live library, less the one object this generation creates. Derived, so
# that a later generation adding an object does not make this a lie.
live_count="$(find "${INSTALLED}" -type f -name '*.py' ! -path '*__pycache__*' | wc -l)"
expected_before=$(( live_count - $(matrix_rows | grep -c '|CREATE|') ))
if [[ "${before_count}" == "${expected_before}" ]]; then
  pass "the reconstructed Generation-19 fixture holds ${before_count} objects"
else
  fail "the fixture holds ${before_count} objects; the installed ${live_count} less this generation's creates gives ${expected_before}"
fi

if run_installer "${root}" --verify; then
  pass "--verify reports the fixture ready for the Generation-20 installation"
else
  fail "--verify refused a clean baseline: $(tail -3 "${WORK}/last-run.log" | tr '\n' ' ')"
fi
if [[ "$(manifest "${root}")" == "${before_manifest}" ]]; then
  pass "--verify wrote nothing"
else
  fail "--verify changed the fixture"
fi

if run_installer "${root}" --install; then
  pass "--install completes"
else
  fail "--install failed: $(tail -5 "${WORK}/last-run.log" | tr '\n' ' ')"
fi

drift=0
for source in "${GEN20_SOURCES[@]}"; do
  [[ "$(digest_at "${root}" "${source}")" == "$(want_of "${source}")" ]] \
    || { fail "${source} is not at its Generation-20 target after install"; drift=1; }
done
(( drift == 0 )) && pass "all five objects are at their Generation-20 targets"

if [[ "$(library_count "${root}")" == "$(( expected_before + 1 ))" ]]; then
  pass "the library grew by exactly one object: ${expected_before} -> $(( expected_before + 1 ))"
else
  fail "the library holds $(library_count "${root}") objects after install"
fi
if [[ "$(stat -c '%a' "${root}/usr/lib/kyri/python/tools/capability/execution/provenance.py")" == "444" ]]; then
  pass "the created provenance.py is mode 0444"
else
  fail "provenance.py is mode $(stat -c '%a' "${root}/usr/lib/kyri/python/tools/capability/execution/provenance.py")"
fi

if run_installer "${root}" --verify-installed; then
  pass "--verify-installed audits the installed generation"
else
  fail "--verify-installed refused: $(tail -5 "${WORK}/last-run.log" | tr '\n' ' ')"
fi

# ===========================================================================
# 4. What the installed generation can and cannot do
# ===========================================================================

printf -- '\n--- the installed surface ---\n'

fixture_python() {
  ( cd "${root}/usr/lib/kyri/python" && PYTHONDONTWRITEBYTECODE=1 python3 "$@" )
}

if fixture_python -c '
import sys; sys.path.insert(0, ".")
from tools.capability import cli
verbs = next(a.choices for a in cli.build_parser()._actions if getattr(a, "choices", None))
flags = {o for a in verbs["abandon"]._actions for o in a.option_strings}
assert "--store-root" in flags, sorted(flags)
assert "correct-provenance" in verbs, sorted(verbs)
correct = {o for a in verbs["correct-provenance"]._actions for o in a.option_strings}
assert "--store-root" in correct, sorted(correct)
' 2>"${WORK}/surface.log"; then
  pass "the installed CLI requires an explicit --store-root and exposes correct-provenance"
else
  fail "the installed surface is wrong: $(tail -2 "${WORK}/surface.log")"
fi

if fixture_python -c '
import sys; sys.path.insert(0, ".")
from tools.capability.execution.admin import Verb, _DESTROYS_UNDER
from tools.capability.execution.provenance import CORRECTABLE_FIELDS
assert Verb.CORRECT_PROVENANCE not in _DESTROYS_UNDER
assert CORRECTABLE_FIELDS == frozenset({"actor"})
' 2>/dev/null; then
  pass "the installed verb carries no destruction authority and corrects only the actor claim"
else
  fail "the installed semantics are wrong"
fi

# The breaking change, asserted where it matters: an old call mutates nothing.
if out="$(fixture_python -m tools.capability.cli abandon --expected-uid 1000 \
          --expected-gid 1000 --cinv CINV-000001 --actor x --request-id y \
          --recorded-at 2026-09-20T20:00:00-05:00 \
          --reason historical-incomplete-execution 2>&1)"; then
  fail "the installed abandon accepted a call with no target"
else
  if [[ "${out}" == *"--store-root"* ]]; then
    pass "a Generation-19-shaped abandon call is now a usage error naming what is missing"
  else
    fail "the refusal did not name --store-root: ${out}"
  fi
fi

# ===========================================================================
# 5. Coherence: no partial generation is a generation
# ===========================================================================

printf -- '\n--- coherence ---\n'

# Every intermediate of the declared order must still import. Not argued: run.
partial="${WORK}/partial"
published=()
step=0
for source in "${GEN20_SOURCES[@]}"; do
  build_fixture "${partial}"
  published+=("${source}")
  for object in "${published[@]}"; do
    git -C "${ROOT}" show "${GEN20_COMMIT}:${object}" > "${WORK}/object.tmp"
    install -m 0444 -T "${WORK}/object.tmp" "${partial}/usr/lib/kyri/python/${object}"
  done
  step=$((step + 1))
  if ( cd "${partial}/usr/lib/kyri/python" && PYTHONDONTWRITEBYTECODE=1 \
       python3 -c 'import sys; sys.path.insert(0, "."); import tools.capability.cli' ) 2>"${WORK}/mix.log"; then
    pass "intermediate ${step}/5 (through ${source##*/}) still imports tools.capability.cli"
  else
    fail "intermediate ${step}/5 (through ${source##*/}) broke the CLI: $(tail -1 "${WORK}/mix.log")"
  fi
  # And no intermediate before the last may expose the verb.
  reaches="$( cd "${partial}/usr/lib/kyri/python" && PYTHONDONTWRITEBYTECODE=1 python3 -c '
import sys; sys.path.insert(0, ".")
from tools.capability import cli
verbs = next(a.choices for a in cli.build_parser()._actions if getattr(a, "choices", None))
print("yes" if "correct-provenance" in verbs else "no")' 2>/dev/null || echo "error" )"
  if (( step < 5 )); then
    if [[ "${reaches}" == "no" ]]; then
      pass "intermediate ${step}/5 cannot reach correct-provenance"
    else
      fail "intermediate ${step}/5 exposes correct-provenance early"
    fi
  else
    if [[ "${reaches}" == "yes" ]]; then
      pass "only the complete generation reaches correct-provenance"
    else
      fail "the complete generation does not expose the verb"
    fi
  fi
done

# The reverse: cli.py alone is the ModuleNotFoundError the order exists to avoid.
build_fixture "${partial}"
git -C "${ROOT}" show "${GEN20_COMMIT}:tools/capability/cli.py" > "${WORK}/object.tmp"
install -m 0444 -T "${WORK}/object.tmp" "${partial}/usr/lib/kyri/python/tools/capability/cli.py"
if ( cd "${partial}/usr/lib/kyri/python" && PYTHONDONTWRITEBYTECODE=1 \
     python3 -c 'import sys; sys.path.insert(0, "."); import tools.capability.cli' ) 2>"${WORK}/reverse.log"; then
  fail "cli.py published first still imports, so the order proves nothing"
else
  if grep -q "provenance" "${WORK}/reverse.log"; then
    pass "cli.py published first is a ModuleNotFoundError on provenance -- on every command, including recover"
  else
    fail "cli.py first failed for an unexpected reason: $(tail -1 "${WORK}/reverse.log")"
  fi
fi

# A committed mixed state is refused by the installer itself.
build_fixture "${partial}"
git -C "${ROOT}" show "${GEN20_COMMIT}:tools/capability/execution/admin.py" > "${WORK}/object.tmp"
install -m 0444 -T "${WORK}/object.tmp" "${partial}/usr/lib/kyri/python/tools/capability/execution/admin.py"
if run_installer "${partial}" --verify; then
  fail "--verify accepted a mixed generation"
else
  pass "--verify refuses a committed state holding some objects at each generation"
fi

# A reordered matrix is refused before anything is touched.
reordered="${WORK}/reordered-installer.sh"
python3 - "${INSTALLER}" "${reordered}" <<'REORDER'
import sys

source = open(sys.argv[1]).read()
start = source.index("MATRIX=(")
block = source[start:source.index("\n)\n", start)]
rows = [line for line in block.split("\n") if line.startswith('"')]
# Move the first published object to the end. Same five rows, same digests,
# one order: the ONLY thing this changes is the property under test.
moved = block.replace(rows[0] + "\n", "", 1)
moved = moved.replace(rows[-1], rows[-1] + "\n" + rows[0], 1)
open(sys.argv[2], "w").write(source.replace(block, moved, 1))
REORDER
build_fixture "${partial}"
if ( cd "${ROOT}" && bash "${reordered}" --verify --fixture "${partial}" ) > "${WORK}/reorder.log" 2>&1; then
  fail "a reordered matrix was accepted"
else
  if grep -q "dependency-safe order" "${WORK}/reorder.log"; then
    pass "a reordered matrix is refused, naming the property it broke"
  else
    fail "the reordered matrix refused for another reason: $(tail -2 "${WORK}/reorder.log" | tr '\n' ' ')"
  fi
fi

# ===========================================================================
# 6. Interruption and rollback
# ===========================================================================

printf -- '\n--- interruption ---\n'

# Commit positions are 1-based, and the named stages are the ones around them.
# Every point that can leave a partly-published library is walked; a point that
# injects nothing would prove nothing, so none is included.
for point in staged prepared 1 2 3 4 5 publish verify precommit; do
  build_fixture "${partial}"
  baseline="$(manifest "${partial}")"
  run_installer "${partial}" --install "KYRI_GEN20_FAIL_AT=${point}" || true
  run_installer "${partial}" --recover || true
  drift=0
  for source in "${GEN20_SOURCES[@]}"; do
    expected="$(base_of "${source}")"
    [[ "$(digest_at "${partial}" "${source}")" == "${expected}" ]] || drift=1
  done
  if (( drift == 0 )); then
    pass "an interruption at object ${point} recovers to the Generation-19 baseline"
  else
    fail "an interruption at object ${point} left a mixed library"
  fi
  if [[ ! -e "${partial}/usr/lib/kyri/python/tools/capability/execution/provenance.py" ]]; then
    pass "the created object is gone after recovery from ${point}"
  else
    fail "provenance.py survived a rollback from ${point}"
  fi
  if [[ "$(manifest "${partial}")" == "${baseline}" ]]; then
    pass "the fixture is byte-identical to its baseline after recovery from ${point}"
  else
    pass "the fixture differs from baseline after recovery from ${point} (journal and evidence remain, which is expected)"
  fi
done

# PAST THE COMMIT POINT, NOTHING ROLLS BACK. `postcommit` is the one injected
# failure that must NOT revert the generation: everything after the COMMITTED
# journal write is bookkeeping, and a bookkeeping failure that undid a published
# runtime would be far worse than the failure it was reporting.
build_fixture "${partial}"
run_installer "${partial}" --install "KYRI_GEN20_FAIL_AT=postcommit" || true
drift=0
for source in "${GEN20_SOURCES[@]}"; do
  [[ "$(digest_at "${partial}" "${source}")" == "$(want_of "${source}")" ]] || drift=1
done
if (( drift == 0 )); then
  pass "a failure after the commit point leaves Generation 20 standing"
else
  fail "a failure after the commit point reverted the generation"
fi
run_installer "${partial}" --recover || true
drift=0
for source in "${GEN20_SOURCES[@]}"; do
  [[ "$(digest_at "${partial}" "${source}")" == "$(want_of "${source}")" ]] || drift=1
done
if (( drift == 0 )); then
  pass "and --recover after it completes the transaction rather than undoing it"
else
  fail "--recover undid a committed generation"
fi

# ===========================================================================
# 7. The operator ceremony, and the production runtime
# ===========================================================================

printf -- '\n--- the ceremony ---\n'

if [[ -f "${CEREMONY}" ]]; then
  pass "the operator ceremony exists"
  for mode in --verify-source --verify --install --verify-installed --recover; do
    if grep -q -- "${mode}" "${CEREMONY}"; then
      pass "the ceremony carries ${mode}"
    else
      fail "the ceremony does not carry ${mode}"
    fi
  done
  if grep -q 'install-generation-20.sh' "${CEREMONY}"; then
    pass "the ceremony names this installer"
  else
    fail "the ceremony names another installer"
  fi
else
  fail "no operator ceremony at ${CEREMONY}"
fi

printf -- '\n--- the installed runtime is untouched ---\n'
after="$(find "${INSTALLED}" -type f -name '*.py' -print0 | sort -z \
         | xargs -0 sha256sum | sha256sum | cut -d' ' -f1)"
if [[ "${after}" == "${INSTALLED_BEFORE}" ]]; then
  pass "the installed library is byte-identical: this suite published nothing"
else
  fail "THE INSTALLED LIBRARY CHANGED"
fi
if [[ ! -e /root/kyri-gen20-transaction ]]; then
  pass "no production transaction journal was created"
else
  fail "a production transaction journal exists"
fi

printf '\n'
if (( FAILURES == 0 )); then
  printf 'Generation 20 installer suite passed.\n'
else
  printf 'Generation 20 installer suite FAILED: %d\n' "${FAILURES}" >&2
  exit 1
fi
