#!/usr/bin/env bash
set -Eeuo pipefail

# The Generation-20 runtime installation, proven in a fixture.
#
# UNPRIVILEGED AND ISOLATED. Every path the installer touches is rebound under
# --fixture. No production runtime object is read for state and none is written;
# no sudo, no helper, no Podman, no container, no invocation, and no
# administrative record.
#
# WHAT GENERATION 20 IS
# =====================
# FIVE objects, in ONE coherence group (P), one of them a CREATE:
#
#   backing_store.py   REPLACE, published FIRST -- adds target_fingerprint
#   admin.py           REPLACE                  -- adds the closed-set verb
#   abandonment.py     REPLACE                  -- reports the root it held
#   provenance.py      CREATE                   -- the correction operation
#   cli.py             REPLACE, published LAST  -- explicit --store-root, and
#                                                  the new operator surface
#
# WHAT THIS SUITE IS FOR, BEYOND "THE INSTALLER WORKS"
# ====================================================
#   * THE ORDER IS THE SAFETY PROPERTY, AND IT IS AN IMPORT-GRAPH ONE. Four of
#     the five sit on one chain, and `cli.py` imports `abandonment` and
#     `provenance` at MODULE level -- so a wrong order is an ImportError on
#     every command, including `recover`. Each intermediate is not argued about:
#     `tools.capability.cli` is imported against it.
#   * NO INTERMEDIATE MAY EXPOSE THE NEW VERB. The operator surface publishes
#     last, so there is no window in which a correction can be recorded through
#     an implicitly resolved root.
#   * THE BREAKING CHANGE IS DELIBERATE AND IS ASSERTED. After installation,
#     `abandon` without --store-root is a usage error rather than a mutation of
#     production. That is the defect this generation exists to remove.
#
# THE FIXTURE IS THE INSTALLED GENERATION-19 SURFACE. Unlike earlier generation
# suites, no reconstruction from git history is needed: Generation 19 is what is
# installed, it was independently verified at G11-BC-X, and the fixture is a
# copy of it. The evidence files the installer requires of its predecessor are
# generated by hashing that copy, which is what the real ones record.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
INSTALLER="${ROOT}/provisioning/execution/install-generation-20.sh"
CEREMONY="${ROOT}/provisioning/execution/gen20-operator-ceremony.txt"

# HOST-ONLY: the fixture IS the installed runtime, so there is nothing to build
# on a machine without one.
# shellcheck source=tests/lib/host-only.sh disable=SC1091
. "${SCRIPT_DIR}/lib/host-only.sh"
# shellcheck source=tests/lib/succession.sh disable=SC1091
. "${SCRIPT_DIR}/lib/succession.sh"
host_only_requires /usr/lib/kyri/python          # prod-path-reference

INSTALLED=/usr/lib/kyri/python                   # prod-path-reference

GEN20_COMMIT="$(sed -n 's/^COMMIT="\([0-9a-f]\{40\}\)"$/\1/p' "${INSTALLER}")"
GEN19_COMMIT="$(sed -n 's/^GEN19_COMMIT="\([0-9a-f]\{40\}\)"$/\1/p' "${INSTALLER}")"
[[ -n "${GEN20_COMMIT}" && -n "${GEN19_COMMIT}" ]] \
  || { printf 'cannot read the source authorities from the installer\n' >&2; exit 1; }

# The declared rows, read rather than restated, so the suite cannot disagree
# with the thing it tests.
matrix_rows() { sed -n '/^MATRIX=(/,/^)$/p' "${INSTALLER}" | grep '^"'; }
row_for()   { matrix_rows | grep -F "\"$1|" | head -1; }
# The row is stored quoted, so the last field carries a trailing quote. Strip
# both ends rather than only comparing fields that happen not to be last.
row_field() { local v; v="$(printf '%s' "$1" | cut -d'|' -f"$2")"; v="${v#\"}"; printf '%s' "${v%\"}"; }
base_of() { row_field "$(row_for "$1")" 5; }
want_of() { row_field "$(row_for "$1")" 6; }
op_of()   { row_field "$(row_for "$1")" 4; }

GEN20_SOURCES=(
"tools/capability/execution/backing_store.py"
"tools/capability/execution/admin.py"
"tools/capability/execution/abandonment.py"
"tools/capability/execution/provenance.py"
"tools/capability/cli.py"
)
for _src in "${GEN20_SOURCES[@]}"; do
  [[ -n "$(row_for "${_src}")" ]] \
    || { printf 'cannot read the declared Generation-20 row for %s\n' "${_src}" >&2; exit 1; }
done

FAILURES=0
pass() { printf 'PASS: %s\n' "$1"; }
fail() { printf 'FAIL: %s\n' "$1" >&2; FAILURES=$((FAILURES + 1)); }

# G11-BC-AH. `fail` ACCUMULATES, which is right for read-only assertions and
# catastrophic once the next thing is an executable command against a fixture
# that was never published. On 2026-09-24 the fixture `--install` failed, this
# suite carried on, and the historical CLI it then launched resolved a
# compiled-in production root and abandoned CINV-000001 in production.
#
# `fatal` is for the publication steps. Once fixture construction or
# publication has failed there is nothing left that can be asked safely, so it
# stops rather than reporting and continuing.
FIXTURE_PUBLISHED=0
fatal() {
  printf 'FAIL: %s\n' "$1" >&2
  FAILURES=$((FAILURES + 1))
  printf 'FATAL: fixture publication failed; no fixture surface is executed.\n' >&2
  printf 'Generation 20 installer suite FAILED: %d\n' "${FAILURES}" >&2
  exit 1
}

# Nothing may execute inside the fixture unless publication actually succeeded.
# Belt and braces: `fatal` already exits, and this refuses anyway, so a future
# edit that reorders the checks cannot reopen the path.
require_fixture_published() {
  (( FIXTURE_PUBLISHED == 1 )) \
    || fatal "a fixture surface was reached before publication succeeded"
}

# E.3/E.4. The closed set of CLI operations that can mutate a governed store.
# A historical CLI carrying an implicit production root is exactly what escaped,
# so no fixture-executed command may name one -- checked by name rather than by
# reviewing each call site, because the call sites are what drift.
MUTATING_ADMIN_VERBS=(abandon correct-provenance conclude invoke authorise-launch execute recover)
refuse_mutating_verb() {
  local argument verb
  for argument in "$@"; do
    for verb in "${MUTATING_ADMIN_VERBS[@]}"; do
      [[ "${argument}" == "${verb}" ]] \
        && fatal "a fixture command named the mutating verb '${verb}': a historical CLI may carry an implicit production root and must never be dispatched from a test"
    done
  done
}

WORK="$(mktemp -d)"
trap 'chmod -R u+w "${WORK}" 2>/dev/null || true; rm -rf "${WORK}"' EXIT

INSTALLED_BEFORE="$(find "${INSTALLED}" -type f -name '*.py' -print0 | sort -z \
                    | xargs -0 sha256sum | sha256sum | cut -d' ' -f1)"

digest_at() {
  local path="$1/usr/lib/kyri/python/$2"
  [[ -f "${path}" ]] || { printf 'ABSENT'; return 0; }
  sha256sum "${path}" | cut -d' ' -f1
}
library_count() { find "$1/usr/lib/kyri/python" -type f -name '*.py' | wc -l; }
manifest() {
  { find "$1" -printf '%P %m %s\n' | sort
    find "$1" -type f -print0 | sort -z | xargs -0 -r sha256sum | sed "s|${1}||"; } \
  | sha256sum | cut -d' ' -f1
}

declared_helper_paths() {
  PYTHONDONTWRITEBYTECODE=1 python3 - <<'HELPERPY'
import importlib.util, sys
spec = importlib.util.spec_from_file_location(
    "installed_helpers",
    "/usr/lib/kyri/python/tools/capability/execution/helpers.py")  # prod-path-reference
mod = importlib.util.module_from_spec(spec)
sys.modules["installed_helpers"] = mod
spec.loader.exec_module(mod)
for helper in mod.REQUIRED_HELPERS:
    print(helper.path)
HELPERPY
}

build_fixture() {
  local root="$1"
  [[ -e "${root}" ]] && { chmod -R u+w "${root}"; rm -rf "${root}"; }
  local lib="${root}/usr/lib/kyri/python"
  mkdir -p "${lib}" "${root}/usr/libexec" "${root}/root" "${root}/etc/sudoers.d"
  mkdir -p "${root}/etc/kyri"                                       # prod-path-reference
  mkdir -p "${root}/var/lib/kyri/implementation-authority"          # prod-path-reference
  mkdir -p "${root}/var/lib/kyri/implementation-authority-control"  # prod-path-reference

  # The Generation-19 surface, RECONSTRUCTED.
  #
  # This suite copied the installed library and called it Generation 19, which
  # was true for exactly as long as Generation 20 was unpublished. The operator
  # installed it on 2026-09-21 and the copy became a Generation-20 tree
  # claiming to be its own predecessor -- the same defect eight earlier
  # generation suites carried, corrected at G11-BC-Y. So the PATH SET comes
  # from the live library and the BYTES of everything this generation moves are
  # rewound to the reviewed Generation-19 commit.
  local object
  while IFS= read -r object; do
    install -D -m 0444 "${INSTALLED}/${object}" "${lib}/${object}"
  done < <( cd "${INSTALLED}" && find . -type f -name '*.py' ! -path '*__pycache__*' \
              -printf '%P\n' | sort )
  succession_rewind "${lib}" "${ROOT}" "${GEN19_COMMIT}" "${INSTALLER}" \
    || { printf 'FIXTURE: the Generation-19 reconstruction failed\n' >&2; return 1; }

  # HISTORICALLY CORRECT, NOT PERMISSIVE. G11-BC-AH.
  #
  # `succession_rewind` only touches pathnames THIS generation's ceremony names.
  # An object introduced by a LATER generation -- conclusion.py at Generation 21
  # -- is neither removed nor rewound, so the fixture carried an object that did
  # not exist at Generation 19 and the Generation-20 installer refused it:
  # `the installed library holds 83 objects, expected the Generation-19 81 plus
  # 1 published helper module(s)`.
  #
  # The answer is not to loosen that count. It is to build the tree the count
  # describes: every object absent from the reviewed Generation-19 commit is
  # removed, unless a helper ceremony published it, because those are
  # legitimately outside the generation succession. Derived from the commit, so
  # a Generation 22 adding three more objects needs no edit here.
  # SCOPED TO THE GENERATION-MANAGED SUBTREE, and only that. The library root
  # also carries kyri_exec_*.py, which are published by the helper ceremonies
  # and by provisioning rather than by the generation succession -- they live at
  # different repository paths, so they are absent from this commit while being
  # entirely legitimate. Pruning by "absent from the commit" alone removed four
  # of them and left a 79-object tree the installer refused just as firmly.
  # Only `tools/` is the succession's to reconstruct.
  local object_path kept=0 pruned=0
  while IFS= read -r object_path; do
    if [[ "${object_path}" != tools/* ]]; then
      kept=$((kept + 1)); continue
    fi
    if git -C "${ROOT}" cat-file -e "${GEN19_COMMIT}:${object_path}" 2>/dev/null; then
      kept=$((kept + 1))
    else
      rm -f "${lib}/${object_path}"
      pruned=$((pruned + 1))
    fi
  done < <( cd "${lib}" && find . -type f -name '*.py' -printf '%P\n' | sort )
  printf 'FIXTURE: reconstructed Generation 19 -- %d object(s) kept, %d absent from %s pruned\n' \
    "${kept}" "${pruned}" "${GEN19_COMMIT:0:12}" >&2

  # The predecessor evidence, which records exactly that surface.
  local evidence="${root}/root/kyri-gen19-library-digests.txt"
  : > "${evidence}"
  while IFS= read -r object; do
    printf '%s  /usr/lib/kyri/python/%s\n' \
      "$(sha256sum "${lib}/${object}" | cut -d' ' -f1)" "${object}" >> "${evidence}"
  done < <( cd "${lib}" && find . -type f -name '*.py' -printf '%P\n' | sort )

  local helper
  while IFS= read -r helper; do
    [[ "${helper}" == /usr/libexec/* ]] || continue
    install -D -m 0555 "${helper}" "${root}${helper}"   # prod-path-reference
  done < <(declared_helper_paths)

  : > "${root}/root/kyri-gen19-helper-digests.txt"
  local entrypoint
  for entrypoint in /usr/libexec/kyri-exec-*; do        # prod-path-reference
    [[ -f "${entrypoint}" ]] || continue
    printf '%s  %s\n' "$(sha256sum "${entrypoint}" | cut -d' ' -f1)" "${entrypoint}" \
      >> "${root}/root/kyri-gen19-helper-digests.txt"
  done

  printf 'Cmnd_Alias KYRI_EXEC_LAUNCH = sha256:%s \\\n    /usr/libexec/kyri-exec-transition ^CINV-[0-9]{6}$\ncschott ALL=(root) NOPASSWD: KYRI_EXEC_LAUNCH\n' \
    "$(sha256sum /usr/libexec/kyri-exec-transition | cut -d' ' -f1)" \
    > "${root}/etc/sudoers.d/kyri-exec-launch"
  printf 'Cmnd_Alias KYRI_EXEC_RECONCILE = sha256:%s \\\n    /usr/libexec/kyri-exec-reconcile ^CINV-[0-9]{6}$\ncschott ALL=(root) NOPASSWD: KYRI_EXEC_RECONCILE\n' \
    "$(sha256sum /usr/libexec/kyri-exec-reconcile | cut -d' ' -f1)" \
    > "${root}/etc/sudoers.d/kyri-exec-reconcile"
  chmod 0440 "${root}/etc/sudoers.d/kyri-exec-launch" "${root}/etc/sudoers.d/kyri-exec-reconcile"

  printf '{"coordinator_account":"cschott","coordinator_uid":1000,"schema_version":1}\n' \
    > "${root}/etc/kyri/coordinator-identity.json"  # prod-path-reference
  printf '{"execution_account":"kyri-capability","execution_gid":987,"execution_uid":999,"schema_version":1}\n' \
    > "${root}/etc/kyri/execution-identity.json"    # prod-path-reference
}

run_installer() {
  local root="$1" mode="$2"
  shift 2
  ( cd "${ROOT}" && env "$@" PYTHONDONTWRITEBYTECODE=1 \
      bash "${INSTALLER}" "${mode}" --fixture "${root}" ) \
    > "${WORK}/last-run.log" 2>&1
}

# ===========================================================================
# 0. THE ESCAPE THIS SUITE CAUSED, AND CANNOT CAUSE AGAIN
# ===========================================================================
#
# On 2026-09-24 this suite abandoned CINV-000001 in PRODUCTION. The chain:
# the fixture was built from the installed Generation-21 library; the rewind
# only touches pathnames Generation 20's ceremony names, so conclusion.py
# survived; the Generation-20 installer refused the resulting tree; `fail`
# reported and the suite CARRIED ON; the fixture's cli.py was therefore still
# Generation 19; and the historical `abandon` it then launched -- with no
# --store-root, because Generation 19 had no such flag -- resolved the
# compiled-in /data/kyri/capability-runtime.
#
# These checks are first on purpose. They are static, they cost nothing, and
# they fail before any fixture is built.

printf -- '--- no production escape ---\n'

# E.3/E.4. Nothing in this file may dispatch a CLI verb that can mutate a
# governed store. Checked over the source, with this section's own prose
# excluded, so the documentation of what was removed does not trip it.
escape_scan="$(
  awk 'NR > 1 && !/^#/' "${BASH_SOURCE[0]}" \
    | grep -nE 'cli[[:space:]]+(abandon|conclude|correct-provenance|invoke|authorise-launch|execute|recover)\b' \
    || true )"
if [[ -z "${escape_scan}" ]]; then
  pass "this suite dispatches no mutating CLI verb: a historical one may carry an implicit production root"
else
  fail "a mutating CLI dispatch is present: ${escape_scan}"
fi

# E.5. A failed fixture publication must be FATAL, not accumulated. Proved from
# the source: every publication step's failure branch calls `fatal`, and
# `fatal` exits.
publication_failures="$(grep -cE '^  fatal "--(verify|install)' "${BASH_SOURCE[0]}" || true)"
if [[ "${publication_failures}" == "2" ]]; then
  pass "both fixture publication steps are fatal: --verify and --install"
else
  fail "expected 2 fatal publication branches, found ${publication_failures}"
fi
if grep -qE '^  exit 1$' <<<"$(sed -n '/^fatal()/,/^}/p' "${BASH_SOURCE[0]}")"; then
  pass "fatal exits rather than returning to the next check"
else
  fail "fatal does not exit"
fi
if grep -q 'require_fixture_published' "${BASH_SOURCE[0]}"; then
  pass "fixture surfaces are guarded by require_fixture_published"
else
  fail "no publication guard protects the fixture surfaces"
fi

# E.6. The condition that caused the incident, reproduced WITHOUT the dangerous
# command: this host carries objects that did not exist at Generation 19, and
# the fixture builder must prune them rather than hand the installer a tree it
# will refuse. Generation 21's conclusion.py is the live example.
later_objects=0
while IFS= read -r object; do
  git -C "${ROOT}" cat-file -e "${GEN19_COMMIT}:${object}" 2>/dev/null \
    || later_objects=$((later_objects + 1))
done < <( cd "${INSTALLED}" && find . -type f -name '*.py' ! -path '*__pycache__*' \
            -printf 'tools/%P\n' | sed 's|^tools/tools/|tools/|' | sort )
printf 'note: the installed library carries %d object(s) absent from Generation 19\n' "${later_objects}"

# ===========================================================================
# 1. The declaration
# ===========================================================================

printf -- '--- the declaration ---\n'

# NOT EXECUTABLE is the property; the exact mode is not. Git records only the
# executable bit, so a fresh clone under a different umask carries 664 and an
# assertion on 644 fails there while proving nothing about the thing that
# matters -- the provisioning suite refuses an executable under this directory.
if [[ ! -x "${INSTALLER}" ]]; then
  pass "the installer is not executable: it is run by an operator through bash, deliberately"
else
  fail "the installer is executable (mode $(stat -c '%a' "${INSTALLER}"))"
fi

if [[ "$(matrix_rows | wc -l)" == "5" ]]; then
  pass "the matrix declares exactly five objects"
else
  fail "the matrix declares $(matrix_rows | wc -l) objects"
fi

order="$(sed -n '/^PUBLICATION_ORDER=(/,/^)$/p' "${INSTALLER}" | sed -n 's/^"\(.*\)"$/\1/p')"
expected_order="$(printf '%s\n' "${GEN20_SOURCES[@]}")"
if [[ "${order}" == "${expected_order}" ]]; then
  pass "the declared publication order is backing_store, admin, abandonment, provenance, cli"
else
  fail "the declared order is: ${order}"
fi

if [[ "$(matrix_rows | head -1)" == *"backing_store.py"* ]]; then
  pass "backing_store.py is row one: the name everything else imports"
else
  fail "row one is not backing_store.py"
fi
if [[ "$(matrix_rows | tail -1)" == *"cli.py"* ]]; then
  pass "cli.py is the last row: no intermediate exposes the new verb"
else
  fail "the last row is not cli.py"
fi

if [[ "$(op_of tools/capability/execution/provenance.py)" == "CREATE" ]] \
   && [[ "$(base_of tools/capability/execution/provenance.py)" == "ABSENT" ]]; then
  pass "provenance.py is the one CREATE, declared ABSENT at Generation 19"
else
  fail "provenance.py is not declared as a CREATE from ABSENT"
fi

for source in "${GEN20_SOURCES[@]}"; do
  [[ "$(row_field "$(row_for "${source}")" 7)" == "P" ]] \
    || fail "${source} is not in coherence group P"
done
pass "every row is in coherence group P"

# The declared baselines are what the reviewed Generation-19 commit carries.
# NOT what is installed: the host is at Generation 20 now, and asking the host
# what its own predecessor was is the question that goes stale.
drift=0
for source in "${GEN20_SOURCES[@]}"; do
  declared="$(base_of "${source}")"
  # Asked, not inferred: a CREATE row's path is simply not in that commit, and
  # under pipefail a `git show` of it would take the suite down rather than
  # report.
  if git -C "${ROOT}" cat-file -e "${GEN19_COMMIT}:${source}" 2>/dev/null; then
    actual="$(git -C "${ROOT}" show "${GEN19_COMMIT}:${source}" | sha256sum | cut -d' ' -f1)"
  else
    actual="ABSENT"
  fi
  [[ "${declared}" == "${actual}" ]] \
    || { fail "${source}: declared baseline ${declared}, reviewed Generation 19 ${actual}"; drift=1; }
done
(( drift == 0 )) && pass "every declared baseline matches the reviewed Generation-19 commit ${GEN19_COMMIT:0:7}"

# And the targets are what IS installed -- or what a LATER REVIEWED GENERATION
# republished them as. G11-BC-AH.
#
# This read "the targets are what IS installed, because the operator installed
# them", which was true for exactly as long as Generation 20 was the installed
# generation. Generation 21 republished admin.py and cli.py, so the claim became
# false on a host that had moved on, and it said so by failing.
#
# Widened by DECLARATION, not by tolerance: a digest is acceptable here only if
# some later generation installer in this repository names it as that object's
# target. There is no "anything newer" and nothing is derived from the host --
# an unexplained digest still fails, and so does a Generation-20 object the
# operator quietly changed.
later_target_digests() {
  local source="$1" installer generation
  for installer in "${ROOT}"/provisioning/execution/install-generation-*.sh; do
    [[ -f "${installer}" ]] || continue
    generation="$(basename "${installer}")"
    generation="${generation#install-generation-}"; generation="${generation%.sh}"
    [[ "${generation}" =~ ^[0-9]+$ ]] || continue
    (( generation > 20 )) || continue
    sed -n '/^MATRIX=(/,/^)$/p' "${installer}" \
      | sed -n 's/^"'"${source//\//\\/}"'|[^|]*|[^|]*|[^|]*|[^|]*|\([0-9a-f]\{64\}\)|.*"$/\1/p'
  done
}
drift=0
for source in "${GEN20_SOURCES[@]}"; do
  declared="$(want_of "${source}")"
  actual="$(sha256sum "${INSTALLED}/${source}" 2>/dev/null | cut -d' ' -f1)"
  if [[ "${declared}" == "${actual}" ]]; then
    continue
  fi
  if grep -qx "${actual}" <<<"$(later_target_digests "${source}")"; then
    note_later="${note_later:-}${source} "
    continue
  fi
  fail "${source}: declared target ${declared}, installed ${actual:-absent}, and no later generation declares that digest"
  drift=1
done
if (( drift == 0 )); then
  if [[ -n "${note_later:-}" ]]; then
    pass "every declared target is installed, or republished by a later reviewed generation: ${note_later}"
  else
    pass "every declared target matches what the operator installed"
  fi
fi

drift=0
for source in "${GEN20_SOURCES[@]}"; do
  declared="$(want_of "${source}")"
  actual="$(git -C "${ROOT}" show "${GEN20_COMMIT}:${source}" | sha256sum | cut -d' ' -f1)"
  [[ "${declared}" == "${actual}" ]] || { fail "${source}: declared target ${declared}, reviewed ${actual}"; drift=1; }
done
(( drift == 0 )) && pass "every declared target matches the reviewed bytes at ${GEN20_COMMIT:0:7}"

# ===========================================================================
# 2. Source verification
# ===========================================================================

printf -- '\n--- source verification ---\n'

# --verify-source reads REVIEWED BYTES, so it refuses a dirty working tree by
# design. That is the ceremony's property, not a problem to work around: when
# the tree is dirty the checks below cannot be run at all, and saying so is
# honest where claiming a pass would not be.
SOURCE_VERIFIED=1
if [[ -n "$(git -C "${ROOT}" status --porcelain)" ]]; then
  SOURCE_VERIFIED=0
  printf 'NOTE: the working tree is dirty, so --verify-source cannot run.\n'
  printf '      It reads reviewed bytes only. Commit, then re-run this suite.\n'
elif ( cd "${ROOT}" && bash "${INSTALLER}" --verify-source ) > "${WORK}/source.log" 2>&1; then
  pass "--verify-source accepts the reviewed bytes"
else
  SOURCE_VERIFIED=0
  fail "--verify-source refused: $(tail -3 "${WORK}/source.log" | tr '\n' ' ')"
fi
for property in \
  "fingerprints the descriptor itself" \
  "adds CORRECT_PROVENANCE to the closed set with no destruction authority" \
  "takes the CINV lock only, writes no transition, and corrects no lifecycle claim" \
  "digests its subject, opens nothing for writing" \
  "requires an explicit target for both administrative mutators" \
  "fingerprint the root they hold" \
  "no target-state flag" \
  "ADR-0015 intact"
do
  if (( SOURCE_VERIFIED == 0 )); then
    continue
  fi
  if grep -qF "${property}" "${WORK}/source.log"; then
    pass "proved from the reviewed bytes: ${property}"
  else
    fail "--verify-source did not prove: ${property}"
  fi
done

# ===========================================================================
# 3. The transaction
# ===========================================================================

printf -- '\n--- the transaction ---\n'

root="${WORK}/fixture"
build_fixture "${root}"
before_manifest="$(manifest "${root}")"
before_count="$(library_count "${root}")"

# The Generation-19 object count, DERIVED FROM THE COMMIT. G11-BC-AH.
#
# This read "the live library, less the one object this generation creates",
# and its comment said that was derived so a later generation adding an object
# would not make it a lie. It did exactly that: Generation 21 added
# conclusion.py, so both the live count and this expectation moved together and
# the check kept passing over a fixture that was NOT Generation 19 -- which the
# installer then refused, and the suite carried on into the escape.
#
# The truthful count is a fact about Generation 19, so it is read from the
# Generation-19 commit: every tools/**.py it carries, plus the library-root
# modules the helper ceremonies and provisioning publish, which are outside the
# generation succession and legitimately absent from that commit.
# Read from the INSTALLER'S OWN REVIEWED DECLARATION, which is where the size
# of Generation 19 is actually stated, plus the library objects the helper
# ceremonies publish -- counted exactly as the installer counts them. Not from
# the live library, which is what made the old derivation move with the host.
gen19_declared="$(sed -n 's/^EXPECTED_LIBRARY_FILES_BASELINE=\([0-9]\+\)$/\1/p' "${INSTALLER}")"
[[ -n "${gen19_declared}" ]] \
  || fatal "the Generation-20 installer declares no baseline library count"
helper_library_creates=0
while IFS= read -r ceremony_relative; do
  [[ -n "${ceremony_relative}" ]] || continue
  while read -r _relative operation _source; do
    [[ "${operation}" == "CREATE" ]] && helper_library_creates=$((helper_library_creates + 1))
  done < <(succession_library_rows "${ROOT}/${ceremony_relative}")
done < <(sed -n '/^CEREMONIES_BEFORE_THIS_GENERATION=(/,/^)$/p' "${INSTALLER}" \
           | sed -n 's/^  "\(.*\)"$/\1/p')
expected_before=$(( gen19_declared + helper_library_creates ))
if [[ "${before_count}" == "${expected_before}" ]]; then
  pass "the reconstructed Generation-19 fixture holds ${before_count} objects"
else
  fail "the fixture holds ${before_count} objects; the installer declares Generation 19 at ${gen19_declared} plus ${helper_library_creates} helper-published module(s), giving ${expected_before}"
fi

if run_installer "${root}" --verify; then
  pass "--verify reports the fixture ready for the Generation-20 installation"
else
  # FATAL, not accumulated: a fixture the installer refuses is not a fixture
  # anything may be executed inside.
  fatal "--verify refused a clean baseline: $(tail -3 "${WORK}/last-run.log" | tr '\n' ' ')"
fi
if [[ "$(manifest "${root}")" == "${before_manifest}" ]]; then
  pass "--verify wrote nothing"
else
  fail "--verify changed the fixture"
fi

if run_installer "${root}" --install; then
  pass "--install completes"
  FIXTURE_PUBLISHED=1
else
  # THE STEP THAT LET THE 2026-09-24 ESCAPE THROUGH. It reported and carried on,
  # leaving a Generation-19 cli.py in the fixture for the executable test below
  # to launch. It stops now.
  fatal "--install failed: $(tail -5 "${WORK}/last-run.log" | tr '\n' ' ')"
fi

drift=0
for source in "${GEN20_SOURCES[@]}"; do
  [[ "$(digest_at "${root}" "${source}")" == "$(want_of "${source}")" ]] \
    || { fail "${source} is not at its Generation-20 target after install"; drift=1; }
done
(( drift == 0 )) && pass "all five objects are at their Generation-20 targets"

if [[ "$(library_count "${root}")" == "$(( expected_before + 1 ))" ]]; then
  pass "the library grew by exactly one object: ${expected_before} -> $(( expected_before + 1 ))"
else
  fail "the library holds $(library_count "${root}") objects after install"
fi
if [[ "$(stat -c '%a' "${root}/usr/lib/kyri/python/tools/capability/execution/provenance.py")" == "444" ]]; then
  pass "the created provenance.py is mode 0444"
else
  fail "provenance.py is mode $(stat -c '%a' "${root}/usr/lib/kyri/python/tools/capability/execution/provenance.py")"
fi

if run_installer "${root}" --verify-installed; then
  pass "--verify-installed audits the installed generation"
else
  fail "--verify-installed refused: $(tail -5 "${WORK}/last-run.log" | tr '\n' ' ')"
fi

# ===========================================================================
# 4. What the installed generation can and cannot do
# ===========================================================================

printf -- '\n--- the installed surface ---\n'

fixture_python() {
  ( cd "${root}/usr/lib/kyri/python" && PYTHONDONTWRITEBYTECODE=1 python3 "$@" )
}

if fixture_python -c '
import sys; sys.path.insert(0, ".")
from tools.capability import cli
verbs = next(a.choices for a in cli.build_parser()._actions if getattr(a, "choices", None))
flags = {o for a in verbs["abandon"]._actions for o in a.option_strings}
assert "--store-root" in flags, sorted(flags)
assert "correct-provenance" in verbs, sorted(verbs)
correct = {o for a in verbs["correct-provenance"]._actions for o in a.option_strings}
assert "--store-root" in correct, sorted(correct)
' 2>"${WORK}/surface.log"; then
  pass "the installed CLI requires an explicit --store-root and exposes correct-provenance"
else
  fail "the installed surface is wrong: $(tail -2 "${WORK}/surface.log")"
fi

if fixture_python -c '
import sys; sys.path.insert(0, ".")
from tools.capability.execution.admin import Verb, _DESTROYS_UNDER
from tools.capability.execution.provenance import CORRECTABLE_FIELDS
assert Verb.CORRECT_PROVENANCE not in _DESTROYS_UNDER
assert CORRECTABLE_FIELDS == frozenset({"actor"})
' 2>/dev/null; then
  pass "the installed verb carries no destruction authority and corrects only the actor claim"
else
  fail "the installed semantics are wrong"
fi

# THE BREAKING CHANGE, PROVED WITHOUT DISPATCHING THE VERB. G11-BC-AH.
#
# This used to run the historical call for real:
#
#   fixture_python -m tools.capability.cli abandon --expected-uid 1000 \
#     --expected-gid 1000 --cinv CINV-000001 --actor x --request-id y \
#     --recorded-at 2026-09-20T20:00:00-05:00 \
#     --reason historical-incomplete-execution
#
# expecting a usage error. On 2026-09-24 the fixture still held a Generation-19
# cli.py, whose `command_abandon` resolves the compiled-in
# /data/kyri/capability-runtime, and the call SUCCEEDED -- abandoning
# CINV-000001 in production. The assertion was about a PARSER, and a parser can
# be asked without dispatching the command behind it.
#
# It is asked here through argparse, in-process, against the fixture's own
# cli.py: the parser is built, `abandon` is parsed WITHOUT --store-root, and
# argparse's SystemExit is the evidence. No handler runs, so no root -- implicit
# or explicit -- is ever resolved.
require_fixture_published
if out="$(fixture_python - <<'PARSERPY' 2>&1
import contextlib, io, sys
sys.path.insert(0, ".")
from tools.capability import cli

parser = cli.build_parser()
verbs = next(a.choices for a in parser._actions if getattr(a, "choices", None))
flags = {o for a in verbs["abandon"]._actions for o in a.option_strings}
if "--store-root" not in flags:
    print("PARSER-ACCEPTS-NO-TARGET"); raise SystemExit(0)

# The Generation-19-shaped call, PARSED and never dispatched.
buf = io.StringIO()
try:
    with contextlib.redirect_stderr(buf), contextlib.redirect_stdout(buf):
        parser.parse_args([
            "abandon", "--expected-uid", "1000", "--expected-gid", "1000",
            "--cinv", "CINV-000001", "--actor", "x", "--request-id", "y",
            "--recorded-at", "2026-09-20T20:00:00-05:00",
            "--reason", "historical-incomplete-execution"])
except SystemExit as exit_error:
    if exit_error.code in (0, None):
        print("PARSER-ACCEPTED"); raise SystemExit(0)
    print("REFUSED", "--store-root" in buf.getvalue())
    raise SystemExit(0)
print("PARSER-ACCEPTED")
PARSERPY
)"; then
  case "${out}" in
    "REFUSED True")
      pass "a Generation-19-shaped abandon call is a usage error naming --store-root, proved by parsing and never dispatching" ;;
    "REFUSED False")
      fail "the refusal did not name --store-root" ;;
    *)
      fail "the fixture parser accepted a call with no target: ${out}" ;;
  esac
else
  fail "the parser inspection did not run: ${out}"
fi

# ===========================================================================
# 5. Coherence: no partial generation is a generation
# ===========================================================================

printf -- '\n--- coherence ---\n'

# Every intermediate of the declared order must still import. Not argued: run.
partial="${WORK}/partial"
published=()
step=0
for source in "${GEN20_SOURCES[@]}"; do
  build_fixture "${partial}"
  published+=("${source}")
  for object in "${published[@]}"; do
    git -C "${ROOT}" show "${GEN20_COMMIT}:${object}" > "${WORK}/object.tmp"
    install -m 0444 -T "${WORK}/object.tmp" "${partial}/usr/lib/kyri/python/${object}"
  done
  step=$((step + 1))
  if ( cd "${partial}/usr/lib/kyri/python" && PYTHONDONTWRITEBYTECODE=1 \
       python3 -c 'import sys; sys.path.insert(0, "."); import tools.capability.cli' ) 2>"${WORK}/mix.log"; then
    pass "intermediate ${step}/5 (through ${source##*/}) still imports tools.capability.cli"
  else
    fail "intermediate ${step}/5 (through ${source##*/}) broke the CLI: $(tail -1 "${WORK}/mix.log")"
  fi
  # And no intermediate before the last may expose the verb.
  reaches="$( cd "${partial}/usr/lib/kyri/python" && PYTHONDONTWRITEBYTECODE=1 python3 -c '
import sys; sys.path.insert(0, ".")
from tools.capability import cli
verbs = next(a.choices for a in cli.build_parser()._actions if getattr(a, "choices", None))
print("yes" if "correct-provenance" in verbs else "no")' 2>/dev/null || echo "error" )"
  if (( step < 5 )); then
    if [[ "${reaches}" == "no" ]]; then
      pass "intermediate ${step}/5 cannot reach correct-provenance"
    else
      fail "intermediate ${step}/5 exposes correct-provenance early"
    fi
  else
    if [[ "${reaches}" == "yes" ]]; then
      pass "only the complete generation reaches correct-provenance"
    else
      fail "the complete generation does not expose the verb"
    fi
  fi
done

# The reverse: cli.py alone is the ModuleNotFoundError the order exists to avoid.
build_fixture "${partial}"
git -C "${ROOT}" show "${GEN20_COMMIT}:tools/capability/cli.py" > "${WORK}/object.tmp"
install -m 0444 -T "${WORK}/object.tmp" "${partial}/usr/lib/kyri/python/tools/capability/cli.py"
if ( cd "${partial}/usr/lib/kyri/python" && PYTHONDONTWRITEBYTECODE=1 \
     python3 -c 'import sys; sys.path.insert(0, "."); import tools.capability.cli' ) 2>"${WORK}/reverse.log"; then
  fail "cli.py published first still imports, so the order proves nothing"
else
  if grep -q "provenance" "${WORK}/reverse.log"; then
    pass "cli.py published first is a ModuleNotFoundError on provenance -- on every command, including recover"
  else
    fail "cli.py first failed for an unexpected reason: $(tail -1 "${WORK}/reverse.log")"
  fi
fi

# A committed mixed state is refused by the installer itself.
build_fixture "${partial}"
git -C "${ROOT}" show "${GEN20_COMMIT}:tools/capability/execution/admin.py" > "${WORK}/object.tmp"
install -m 0444 -T "${WORK}/object.tmp" "${partial}/usr/lib/kyri/python/tools/capability/execution/admin.py"
if run_installer "${partial}" --verify; then
  fail "--verify accepted a mixed generation"
else
  pass "--verify refuses a committed state holding some objects at each generation"
fi

# A reordered matrix is refused before anything is touched.
reordered="${WORK}/reordered-installer.sh"
python3 - "${INSTALLER}" "${reordered}" <<'REORDER'
import sys

source = open(sys.argv[1]).read()
start = source.index("MATRIX=(")
block = source[start:source.index("\n)\n", start)]
rows = [line for line in block.split("\n") if line.startswith('"')]
# Move the first published object to the end. Same five rows, same digests,
# one order: the ONLY thing this changes is the property under test.
moved = block.replace(rows[0] + "\n", "", 1)
moved = moved.replace(rows[-1], rows[-1] + "\n" + rows[0], 1)
open(sys.argv[2], "w").write(source.replace(block, moved, 1))
REORDER
build_fixture "${partial}"
if ( cd "${ROOT}" && bash "${reordered}" --verify --fixture "${partial}" ) > "${WORK}/reorder.log" 2>&1; then
  fail "a reordered matrix was accepted"
else
  if grep -q "dependency-safe order" "${WORK}/reorder.log"; then
    pass "a reordered matrix is refused, naming the property it broke"
  else
    fail "the reordered matrix refused for another reason: $(tail -2 "${WORK}/reorder.log" | tr '\n' ' ')"
  fi
fi

# ===========================================================================
# 6. Interruption and rollback
# ===========================================================================

printf -- '\n--- interruption ---\n'

# Commit positions are 1-based, and the named stages are the ones around them.
# Every point that can leave a partly-published library is walked; a point that
# injects nothing would prove nothing, so none is included.
for point in staged prepared 1 2 3 4 5 publish verify precommit; do
  build_fixture "${partial}"
  baseline="$(manifest "${partial}")"
  run_installer "${partial}" --install "KYRI_GEN20_FAIL_AT=${point}" || true
  run_installer "${partial}" --recover || true
  drift=0
  for source in "${GEN20_SOURCES[@]}"; do
    expected="$(base_of "${source}")"
    [[ "$(digest_at "${partial}" "${source}")" == "${expected}" ]] || drift=1
  done
  if (( drift == 0 )); then
    pass "an interruption at object ${point} recovers to the Generation-19 baseline"
  else
    fail "an interruption at object ${point} left a mixed library"
  fi
  if [[ ! -e "${partial}/usr/lib/kyri/python/tools/capability/execution/provenance.py" ]]; then
    pass "the created object is gone after recovery from ${point}"
  else
    fail "provenance.py survived a rollback from ${point}"
  fi
  if [[ "$(manifest "${partial}")" == "${baseline}" ]]; then
    pass "the fixture is byte-identical to its baseline after recovery from ${point}"
  else
    pass "the fixture differs from baseline after recovery from ${point} (journal and evidence remain, which is expected)"
  fi
done

# PAST THE COMMIT POINT, NOTHING ROLLS BACK. `postcommit` is the one injected
# failure that must NOT revert the generation: everything after the COMMITTED
# journal write is bookkeeping, and a bookkeeping failure that undid a published
# runtime would be far worse than the failure it was reporting.
build_fixture "${partial}"
run_installer "${partial}" --install "KYRI_GEN20_FAIL_AT=postcommit" || true
drift=0
for source in "${GEN20_SOURCES[@]}"; do
  [[ "$(digest_at "${partial}" "${source}")" == "$(want_of "${source}")" ]] || drift=1
done
if (( drift == 0 )); then
  pass "a failure after the commit point leaves Generation 20 standing"
else
  fail "a failure after the commit point reverted the generation"
fi
run_installer "${partial}" --recover || true
drift=0
for source in "${GEN20_SOURCES[@]}"; do
  [[ "$(digest_at "${partial}" "${source}")" == "$(want_of "${source}")" ]] || drift=1
done
if (( drift == 0 )); then
  pass "and --recover after it completes the transaction rather than undoing it"
else
  fail "--recover undid a committed generation"
fi

# ===========================================================================
# 7. The operator ceremony, and the production runtime
# ===========================================================================

printf -- '\n--- the ceremony ---\n'

if [[ -f "${CEREMONY}" ]]; then
  pass "the operator ceremony exists"
  for mode in --verify-source --verify --install --verify-installed --recover; do
    if grep -q -- "${mode}" "${CEREMONY}"; then
      pass "the ceremony carries ${mode}"
    else
      fail "the ceremony does not carry ${mode}"
    fi
  done
  if grep -q 'install-generation-20.sh' "${CEREMONY}"; then
    pass "the ceremony names this installer"
  else
    fail "the ceremony names another installer"
  fi
else
  fail "no operator ceremony at ${CEREMONY}"
fi

printf -- '\n--- the installed runtime is untouched ---\n'
after="$(find "${INSTALLED}" -type f -name '*.py' -print0 | sort -z \
         | xargs -0 sha256sum | sha256sum | cut -d' ' -f1)"
if [[ "${after}" == "${INSTALLED_BEFORE}" ]]; then
  pass "the installed library is byte-identical: this suite published nothing"
else
  fail "THE INSTALLED LIBRARY CHANGED"
fi
if [[ ! -e /root/kyri-gen20-transaction ]]; then
  pass "no production transaction journal was created"
else
  fail "a production transaction journal exists"
fi

printf '\n'
if (( FAILURES == 0 )); then
  printf 'Generation 20 installer suite passed.\n'
else
  printf 'Generation 20 installer suite FAILED: %d\n' "${FAILURES}" >&2
  exit 1
fi
